server:
  port: ${PORT}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

spring:
  application:
    name: ${NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER_NAME}
    password: ${RABBITMQ_USER_PASS}
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/api/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - http://localhost:3000
              - http://localhost:3001
              - http://15.164.15.10:8080
              - http://donghun.me:80
              - http://donghun.me:8080
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH            
              - DELETE
              - OPTIONS

jwt:
  secret-key: ${JWT_SECRET_KEY}